name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Que es deploy?
  deploy:
    runs-on: ubuntu-18.04

    # Get my repository
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node version
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run lint (no required)
      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: End-to-end tests
        uses: cypress-io/github-action@v4
        with:
          command: yarn cy:run
          start: yarn start
          wait-on: http://localhost:3000
